# a mybinder.org-ready environment for demoing climb_dashboard_gui
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate climb-usage-extension-demo
#
name: climb-usage-extension-demo

channels:
  - conda-forge

dependencies:
  # runtime dependencies
  - python >=3.13,<3.14.0a0
  - jupyterlab >=4.0.0,<5
  # labextension build dependencies
  - nodejs >=22,<23
  - pip
  - wheel
  # additional packages for demos
  # - ipywidgets
